version: "3.9"

services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.11.2-management
    restart: on-failure
    networks:
      - backend
    env_file:
      - .envs/.env
    ports:
      - 15672:15672

  pg:
    build:
      context: ./postgres
    image: plots418890/natours_pg:0.0.1
    container_name: pg
    networks:
      - backend
    restart: on-failure
    env_file: .envs/.env.db
    volumes:
      - pgdata:/var/lib/postgresql/data

  flower:
    container_name: flower
    depends_on:
      - celeryworker
      - rabbit
    image: plots418890/natours_backend:0.0.1
    networks:
      - backend
    restart: on-failure
    entrypoint:
      ["${PROJECT_PATH?Variable not set}/commands/entrypoint.flower.sh"]
    env_file:
      - .envs/.env
    ports:
      - 5555:5555
    volumes:
      - backend_src:${PROJECT_PATH?Variable not set}

  redis:
    container_name: redis
    depends_on:
      - rabbit
      - backend
      - celeryworker
    entrypoint: ["redis-server"]
    image: redis:7.0-rc-alpine
    networks:
      - backend
    restart: on-failure

  nginx:
    container_name: nginx
    depends_on:
      - backend
    image: nginx:1.22.1
    networks:
      - backend
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx
      - webroot:/var/www/html
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
      - webserver_static:/var/www/natours-club.site/static
      - webserver_media:/var/www/natours-club.site/media

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - webroot:/var/www/html
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email natourstest@mail.ru --agree-tos --force-renewal -v -d natours-club.site -d www.natours-club.site -d api.natours-club.site
    networks:
      - backend

  backend:
    entrypoint: ["${PROJECT_PATH?Variable not set}/commands/entrypoint.sh"]
    image: plots418890/natours_backend:0.0.1
    build:
      context: ./backend/
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
        PROJECT_PATH_ARG: ${PROJECT_PATH?Variable not set}
        DOMAIN_ARG: ${DOMAIN?Variable not set}
    container_name: backend
    env_file:
      - .envs/.env
    depends_on:
      - pg
      - rabbit
    networks:
      - backend
    restart: on-failure
    volumes:
      - backend_src:${PROJECT_PATH?Variable not set}
      - webserver_static:/var/www/natours-club.site/static
      - webserver_media:/var/www/natours-club.site/media

  celeryworker:
    container_name: celeryworker
    entrypoint:
      ["${PROJECT_PATH?Variable not set}/commands/entrypoint.celery.sh"]
    env_file:
      - .envs/.env
    volumes:
      - backend_src:${PROJECT_PATH?Variable not set}
    depends_on:
      - rabbit
      - pg
    image: plots418890/natours_backend:0.0.1
    networks:
      - backend
    restart: on-failure

volumes:
  pgdata:
  certbot_var:
  certbot_etc:
  backend_src:
    driver: local
    driver_opts:
      type: none
      device: ${PROJECT_PATH?Variable not set}/backend/src/
      o: bind
  webserver_media:
    driver: local
    driver_opts:
      type: none
      device: /var/www/natours-club.site/media/
      o: bind
  webserver_static:
    driver: local
    driver_opts:
      type: none
      device: /var/www/natours-club.site/static/
      o: bind
  webroot:
    driver: local
    driver_opts:
      type: none
      device: ${PROJECT_PATH?Variable not set}/frontend/dist/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ${PROJECT_PATH?Variable not set}/certs/
      o: bind

networks:
  backend:
    name: "natours"
